name: Generate Snake Animation

on:
  # run automatically every 01 hours
  schedule: # execute every 01 hours
    - cron: "* */1 * * *"
  
  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      # generate a snake gane
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        id: github-snake
        with:
          github_user_name: asventura96
          outputs: |
            dist/github-snake.svg
      
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
